export const SET_SYSNAME = "SET_SYSNAME"; // 设置系统名

// user 用户
export const SET_USER_INFO = "SET_USERINFO"; // 设置用户信息
export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS"; // 设置登录状态
export const SET_USER_SESSION = "SET_USER_SESSION";

export const SET_CONFIG = "SET_CONFIG"; // 系统配置信息

// 自定义拖拽
export const VISUAL_DRAG_COPY = "VISUAL_DRAG_COPY"; // 粘贴
export const VISUAL_DRAG_PASTE = "VISUAL_DRAG_PASTE";
export const VISUAL_DRAG_CUT = "VISUAL_DRAG_CUT";
export const VISUAL_DRAG_SET_EDIT_MODE = "VISUAL_DRAG_SET_EDIT_MODE";
export const VISUAL_DRAG_SET_CANVAS_STYLE = "VISUAL_DRAG_SET_CANVAS_STYLE";
export const VISUAL_DRAG_ADD_COMPONENT = "VISUAL_DRAG_ADD_COMPONENT";
export const VISUAL_DRAG_SET_CUR_COMPONENT = "VISUAL_DRAG_SET_CUR_COMPONENT";
export const VISUAL_DRAG_SET_SHAPE_STYLE = "VISUAL_DRAG_SET_SHAPE_STYLE";
export const VISUAL_DRAG_SET_SHAPE_POS_STYLE =
  "VISUAL_DRAG_SET_SHAPE_POS_STYLE";
export const VISUAL_DRAG_UNDO = "VISUAL_DRAG_UNDO";
export const VISUAL_DRAG_REDO = "VISUAL_DRAG_REDO";
export const VISUAL_DRAG_SET_COMPONENT_DATA = "VISUAL_DRAG_SET_COMPONENT_DATA";
export const VISUAL_DRAG_RECODE_SNAP_SHOT = "VISUAL_DRAG_RECODE_SNAP_SHOT";
export const VISUAL_DRAG_SHOW_CONTEXT_MENU = "VISUAL_DRAG_SHOW_CONTEXT_MENU";
export const VISUAL_DRAG_HIDE_CONTEXT_MENU = "VISUAL_DRAG_HIDE_CONTEXT_MENU";
export const VISUAL_DRAG_DELETE_COMPONENT = "VISUAL_DRAG_DELETE_COMPONENT";
export const VISUAL_DRAG_UPCOMPONENT = "VISUAL_DRAG_UPCOMPONENT";
export const VISUAL_DRAG_DOWN_COMPONENT = "VISUAL_DRAG_DOWN_COMPONENT";
export const VISUAL_DRAG_TOP_COMPONENT = "VISUAL_DRAG_TOP_COMPONENT";
export const VISUAL_DRAG_BOTTOM_COMPONENT = "VISUAL_DRAG_BOTTOM_COMPONENT";
export const VISUAL_DRAG_ADD_ANIMATION = "VISUAL_DRAG_ADD_ANIMATION";
export const VISUAL_DRAG_REMOVE_ANIMATION = "VISUAL_DRAG_REMOVE_ANIMATION";
export const VISUAL_DRAG_ADD_EVEVT = "VISUAL_DRAG_ADD_EVEVT";
export const VISUAL_DRAG_REMOVE_EVENT = "VISUAL_DRAG_REMOVE_EVENT";
